### ISSUE TITLE
Can't launch model with vLLM 0.8.3

### ISSUE THREAD

**Issue by karlbernard2** [MiniMax-AI/MiniMax-01#42]
Hi, we were thrilled to finally be able to test =running your model locally.

Unfortunately it's erroring out. Do you have any advice on how to launch model on H200?

`docker run -d --runtime nvidia --gpus all \
    --network=host --privileged --ipc=host --ulimit memlock=-1 --shm-size=2gb --ulimit stack=67108864 \
    -e "USE_FASTSAFETENSOR=true" \
    -e "VLLM_USE_V1=0" \
    vllm/vllm-openai:v0.8.3 \
    --model MiniMaxAI/MiniMax-Text-01  \
    --tensor-parallel-size 8 \
    --trust-remote-code \
    --quantization experts_int8 \
    --dtype bfloat16`

Here's a portion of the logs
`(VllmWorkerProcess pid=222) INFO 04-06 20:46:23 [loader.py:447] Loading weights took 836.59 seconds
(VllmWorkerProcess pid=217) INFO 04-06 20:46:24 [loader.py:447] Loading weights took 837.39 seconds
(VllmWorkerProcess pid=222) INFO 04-06 20:46:24 [model_runner.py:1146] Model loading took 62.5309 GiB and 842.568352 seconds
(VllmWorkerProcess pid=217) INFO 04-06 20:46:24 [model_runner.py:1146] Model loading took 62.5309 GiB and 842.614901 seconds
(VllmWorkerProcess pid=222) WARNING 04-06 20:46:33 [fused_moe.py:659] Using default MoE config. Performance might be sub-optimal! Config file not found at /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=32,N=1152,device_name=NVIDIA_H200,dtype=int8_w8a16.json
(VllmWorkerProcess pid=219) WARNING 04-06 20:46:33 [fused_moe.py:659] Using default MoE config. Performance might be sub-optimal! Config file not found at /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=32,N=1152,device_name=NVIDIA_H200,dtype=int8_w8a16.json
WARNING 04-06 20:46:33 [fused_moe.py:659] Using default MoE config. Performance might be sub-optimal! Config file not found at /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=32,N=1152,device_name=NVIDIA_H200,dtype=int8_w8a16.json
(VllmWorkerProcess pid=217) WARNING 04-06 20:46:33 [fused_moe.py:659] Using default MoE config. Performance might be sub-optimal! Config file not found at /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=32,N=1152,device_name=NVIDIA_H200,dtype=int8_w8a16.json
(VllmWorkerProcess pid=223) WARNING 04-06 20:46:33 [fused_moe.py:659] Using default MoE config. Performance might be sub-optimal! Config file not found at /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=32,N=1152,device_name=NVIDIA_H200,dtype=int8_w8a16.json
(VllmWorkerProcess pid=220) WARNING 04-06 20:46:33 [fused_moe.py:659] Using default MoE config. Performance might be sub-optimal! Config file not found at /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=32,N=1152,device_name=NVIDIA_H200,dtype=int8_w8a16.json
(VllmWorkerProcess pid=218) WARNING 04-06 20:46:33 [fused_moe.py:659] Using default MoE config. Performance might be sub-optimal! Config file not found at /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=32,N=1152,device_name=NVIDIA_H200,dtype=int8_w8a16.json
(VllmWorkerProcess pid=221) WARNING 04-06 20:46:33 [fused_moe.py:659] Using default MoE config. Performance might be sub-optimal! Config file not found at /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=32,N=1152,device_name=NVIDIA_H200,dtype=int8_w8a16.json
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238] Exception in worker VllmWorkerProcess while processing method determine_num_available_blocks.
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238] Traceback (most recent call last):
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/multiproc_worker_utils.py", line 232, in _run_worker_process
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     output = run_method(worker, method, args, kwargs)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 2347, in run_method
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker.py", line 229, in determine_num_available_blocks
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     self.model_runner.profile_run()
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1243, in profile_run
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     self._dummy_run(max_num_batched_tokens, max_num_seqs)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1369, in _dummy_run
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     self.execute_model(model_input, kv_caches, intermediate_tensors)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1816, in execute_model
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     logits = self.model.compute_logits(hidden_or_intermediate_states,
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/minimax_text_01.py", line 1028, in compute_logits
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     logits = self.logits_processor(self.lm_head, hidden_states,
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/logits_processor.py", line 70, in forward
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     logits = self._get_logits(hidden_states, lm_head, embedding_bias)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/logits_processor.py", line 113, in _get_logits
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     logits = self._gather_logits(logits)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/logits_processor.py", line 98, in _gather_logits
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     logits = tensor_model_parallel_gather(logits)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/vllm/distributed/communication_op.py", line 26, in tensor_model_parallel_gather
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     return get_tp_group().gather(input_, dst, dim)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/vllm/distributed/parallel_state.py", line 341, in gather
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     return self.device_communicator.gather(input_, dst, dim)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/vllm/distributed/device_communicators/base_device_communicator.py", line 86, in gather
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     torch.distributed.gather(input_,
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/torch/distributed/distributed_c10d.py", line 4006, in gather
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]     work = group.gather(output_tensors, input_tensors, opts)
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=221) ERROR 04-06 20:46:48 [multiproc_worker_utils.py:238] torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/NCCLUtils.hpp:268, unhandled system error (run with NCCL_DEBUG=INFO for details), NCCL version 2.21.5`

**Comment by qscqesze** [comment]
I think maybe NCCL cause this problem. Do you use the official docker？

Could you generate a debug log with NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=ALL and post it here? Also, any chance you could try with a more recent NCCL release?

**Comment by karlbernard2** [comment]
Yes we are using official docker.

Here's some of the debug info. I am using a VM from HPC-AI to test and I can't seem to easily get newer nccl version running from within the container. I'll try with a different cloud provider tomorrow.

[debug.txt](https://github.com/user-attachments/files/19642313/debug.txt)

**Comment by qscqesze** [comment]
> Yes we are using official docker.
> 
> Here's some of the debug info. I am using a VM from HPC-AI to test and I can't seem to easily get newer nccl version running from within the container. I'll try with a different cloud provider tomorrow.
> 
> [debug.txt](https://github.com/user-attachments/files/19642313/debug.txt)

```
NCCL WARN Error while creating shared memory segment /dev/shm/nccl-xxxxx (size 7340384)
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error.
```

A low-level system call failed, likely due to a lack of shared memory or improper permissions.
I think you need to check shared memory (/dev/shm) space.

H200x8 is a big GPU machine. It's enough to run our model.

**Comment by karlbernard2** [comment]
@qscqesze Thanks for your help, I was able to get this working by removing  "--privileged --ipc=host" and adjusting --shm-size=32gb

In case it helps someone, this is working for us on 8xH200
`docker run -it --runtime nvidia --gpus all \
    --network=host --ulimit memlock=-1 --shm-size=32gb\
    -e "USE_FASTSAFETENSOR=true" \
    -e "VLLM_USE_V1=0" \
    vllm/vllm-openai:v0.8.3 \
    --model MiniMaxAI/MiniMax-Text-01  \
    --served-model-name MiniMaxAI/MiniMax-Text-01 \
    --tensor-parallel-size 8 \
    --trust-remote-code \
    --quantization experts_int8 \
    --dtype bfloat16 \
    --enable-prefix-caching`

I did run into another issue, but will create a separate thread.
